### ISSUE TITLE
Only use the GitHub username to find the member from API

### ISSUE THREAD

**Issue by manishram** [nax3t/automated-payroll#11]
Let's only use the GitHub username to find the member from API to get hourly rates.

**Problem**: 
This line of [code](https://github.com/nax3t/automated-payroll/blob/ca34d60a5d8acc2e748522617789b24de4719b75/app.js#L94) is creating a problem because we have `led76marx` and `toledit` in our team with `led` as part of their name.

Due to this reason, `toledit` was receiving the payment with an hourly rate of `led76marx`.

Also, we should get rid of this [code](https://github.com/nax3t/automated-payroll/blob/ca34d60a5d8acc2e748522617789b24de4719b75/app.js#L95) there are possible edge cases for this too.

**Comment by nax3t** [comment]
Added your changes in manually to ensure that existing code was maintained
https://github.com/nax3t/automated-payroll/commit/ea81df073506efb19efc99cd41cb8212d32d1381
